function [pks, locations] = getPeaks( inputSignal, stdThreshold )
    inputSignalStd = std(inputSignal(:));
    [pks, locations] = findpeaks(inputSignal,...
        'minpeakheight', inputSignalStd * stdThreshold,...
        'minpeakdistance', 10,...
        'minpeakprominence', 5,...
        'minpeakwidth', 2);
    
    eventTimeArray = sortrows([pks', locations'], 'descend');
    pks = eventTimeArray(:, 1);
    locations = eventTimeArray(:, 2);

end
